# Generated by Django 3.1.1 on 2020-10-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_twitter_id', models.CharField(max_length=25)),
                ('tweet_id', models.CharField(max_length=25)),
                ('tweet_by', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=25)),
            ],
        ),
    ]
