# Generated by Django 3.1.1 on 2020-10-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='tweetsdetails',
            unique_together={('user_twitter_id', 'tweet_id', 'tweet_by', 'created_at')},
        ),
    ]
