# Generated by Django 3.1.1 on 2020-10-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchproject', '0002_auto_20201003_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetsdetails',
            name='id',
        ),
        migrations.AddField(
            model_name='tweetsdetails',
            name='unique',
            field=models.CharField(default='SOME STRING', max_length=50, primary_key=True, serialize=False),
        ),
    ]
