# Generated by Django 3.1.1 on 2020-10-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchproject', '0003_auto_20201003_0704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tweetsdetails',
            unique_together=set(),
        ),
    ]
